import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import {
  DocumentBuilder,
  COLOURS,
  money,
  kg,
  dateLong,
  num,
  type CompanyInfo,
  type Column,
} from './pdf-core';

export interface RenderedDocument {
  docType: string;
  filename: string;
  buffer: Buffer;
  /** True when this is a real document, false when it is a control sheet. */
  isPrimaryDocument: boolean;
}

/** Elements issued by an authority: we produce the application pack, not the certificate. */
const AUTHORITY_ISSUED = new Set([
  'ICO Certificate of Origin',
  'CLU Quality Certificate',
  'Phytosanitary Certificate',
  'Chamber Certificate of Origin',
  'Fumigation Certificate',
  'Customs Export Declaration',
  'MAFF Plant Quarantine Certificate',
  'MHLW Certificate of Importation',
  'EUR.1 Movement Certificate',
  'CBSA Import Declaration',
]);

/**
 * Generates the printable PDF for every document in an export pack.
 *
 * The distinction between what we generate and what an authority issues is
 * carried into the document itself: an authority application pack is headed
 * "application data" and states plainly that the certificate is issued by the
 * named authority. Nothing here ever renders a document that could be mistaken
 * for a government certificate we are not entitled to produce.
 */
@Injectable()
export class PdfService {
  private logger = new Logger('Pdf');

  constructor(private prisma: PrismaService) {}

  async company(): Promise<CompanyInfo> {
    const setting = await this.prisma.setting.findUnique({ where: { key: 'organization' } });
    const value = (setting?.value ?? {}) as any;
    return {
      name: value.name ?? 'Ancient Halo Coffee Export',
      addressLines: value.addressLines ?? [],
      email: value.email ?? process.env.MAIL_REPLY_TO ?? null,
      phone: value.phone ?? null,
      tin: value.tin ?? null,
    };
  }

  private footer(company: CompanyInfo) {
    return `${company.name} · Generated by Ancient Halo Coffee · ${dateLong(new Date())}`;
  }

  // ── data loading ─────────────────────────────────────────────────────

  private async loadInvoice(id: string) {
    const invoice = await this.prisma.commercialInvoice.findUnique({
      where: { id },
      include: {
        buyer: true,
        lines: true,
        proforma: { include: { lines: true } },
        contract: { select: { id: true, code: true } },
        shipments: { orderBy: { createdAt: 'desc' }, take: 1 },
        documents: true,
      },
    });
    if (!invoice) throw new NotFoundException('Commercial invoice not found');
    return invoice;
  }

  /** Resolve the lots behind an invoice's lines, with station and traceability. */
  private async lotsFor(lines: { lotId?: string | null }[]) {
    const lotIds = [...new Set(lines.map((l) => l.lotId).filter(Boolean))] as string[];
    if (!lotIds.length) return new Map<string, any>();
    const lots = await this.prisma.lot.findMany({
      where: { lotId: { in: lotIds } },
      include: { station: true, documents: true },
    });
    return new Map(lots.map((l) => [l.lotId, l]));
  }

  private invoiceLines(invoice: any) {
    // A converted invoice normally carries its own lines; fall back to the
    // proforma's when conversion predates line copying.
    return invoice.lines?.length ? invoice.lines : (invoice.proforma?.lines ?? []);
  }

  // ── commercial invoice ───────────────────────────────────────────────

  async commercialInvoice(id: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(id);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotMap = await this.lotsFor(lines);

    const b = new DocumentBuilder(
      {
        title: 'Commercial Invoice',
        reference: invoice.code,
        company,
      },
      this.footer(company),
    );

    b.keyValues(
      [
        { label: 'Invoice no.', value: invoice.code },
        { label: 'Invoice date', value: dateLong(invoice.date) },
        { label: 'Buyer', value: invoice.buyer?.name },
        { label: 'Country of destination', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: 'Incoterm', value: invoice.incoterm },
        { label: 'Currency', value: invoice.currency },
        { label: 'HS code', value: invoice.hsCode },
        { label: 'Port of loading', value: invoice.portLoading ?? 'Djibouti' },
        { label: 'Port of discharge', value: invoice.portDischarge ?? '—' },
        { label: 'Proforma reference', value: invoice.proforma?.code ?? '—' },
        { label: 'Contract reference', value: invoice.contract?.code ?? '—' },
        { label: 'Payment terms', value: invoice.paymentTerms ?? invoice.proforma?.paymentTerms ?? '—' },
      ],
      3,
    );

    b.space(6);
    b.sectionTitle('Consignee');
    b.keyValues(
      [
        { label: 'Name', value: invoice.buyer?.name },
        { label: 'Contact', value: invoice.buyer?.contactName },
        { label: 'Country', value: invoice.buyer?.country },
        { label: 'Email', value: invoice.buyer?.email },
      ],
      2,
    );

    b.space(4);
    b.sectionTitle('Goods');

    const columns: Column[] = [
      { header: '#', width: 0.04, render: (_r, i) => String(i + 1) },
      { header: 'Lot', width: 0.18, key: 'lotId' },
      { header: 'Description', width: 0.26, key: 'description' },
      { header: 'Grade', width: 0.14, render: (r) => {
          const l = r.lotId ? lotMap.get(r.lotId) : null;
          return [l?.grade, l?.screenSize].filter(Boolean).join(' · ') || '—';
        } },
      { header: 'Qty (kg)', width: 0.13, align: 'right', render: (r) => num(r.quantityKg) },
      { header: 'Unit', width: 0.1, align: 'right', render: (r) => num(r.pricePerKg) },
      { header: 'Amount', width: 0.15, align: 'right', render: (r) => money(r.amount, invoice.currency) },
    ];

    const total = lines.reduce((a: number, l: any) => a + Number(l.amount ?? 0), 0);
    const totalKg = lines.reduce((a: number, l: any) => a + Number(l.quantityKg ?? 0), 0);
    const avg = totalKg > 0 ? total / totalKg : 0;

    b.table({
      columns,
      rows: lines,
      emptyText: 'No line items.',
      footRows: [
        ['Total net weight', kg(totalKg)],
        ['Average unit price', `${money(avg, invoice.currency)} / kg`],
        ['TOTAL', money(total, invoice.currency)],
      ],
    });

    b.space(4);
    b.sectionTitle('Amount in words');
    b.paragraph(amountInWords(total, invoice.currency), { size: 9.5 });

    const originLots = [...lotMap.values()];
    const origins = [...new Set(originLots.map((l) => l.origin ?? l.region).filter(Boolean))];
    if (origins.length) {
      b.space(2);
      b.keyValues(
        [
          { label: 'Origin', value: origins.join(', ') },
          { label: 'Harvest year', value: [...new Set(originLots.map((l) => l.harvestYear).filter(Boolean))].join(', ') },
        ],
        2,
      );
    }

    b.space(4);
    b.note(
      `We certify that the goods described above are of Ethiopian origin and that this invoice is true and correct. ` +
        `Country of origin: Ethiopia. HS code ${invoice.hsCode}. Goods sold ${invoice.incoterm} ${invoice.portDischarge ?? invoice.destinationCountryName ?? ''}.`,
      'info',
    );
    b.signatureBlock({ labels: ['For and on behalf of', 'Date'] });

    return {
      docType: 'Commercial Invoice',
      filename: `${invoice.code}-commercial-invoice.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── packing list ─────────────────────────────────────────────────────

  async packingList(id: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(id);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotMap = await this.lotsFor(lines);

    const b = new DocumentBuilder(
      { title: 'Packing List', reference: invoice.code, company },
      this.footer(company),
    );

    b.keyValues(
      [
        { label: 'Invoice no.', value: invoice.code },
        { label: 'Date', value: dateLong(invoice.date) },
        { label: 'Buyer', value: invoice.buyer?.name },
        { label: 'Destination', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: 'Container no.', value: invoice.shipments?.[0]?.containerNo ?? '—' },
        { label: 'Seal no.', value: invoice.shipments?.[0]?.sealNo ?? '—' },
      ],
      3,
    );

    b.space(6);
    b.sectionTitle('Packed goods');

    const rows = lines.map((line: any) => {
      const lot = line.lotId ? lotMap.get(line.lotId) : null;
      const net = Number(lot?.netWeightKg ?? line.quantityKg ?? 0);
      // Export coffee moves in 60 kg bags; derive the count when the lot does
      // not record it, and mark the derivation so the figure is not mistaken
      // for a measured one.
      const derivedBags = Math.ceil(net / 60);
      const bags = lot?.bagCount ?? derivedBags;
      const gross = Number(lot?.grossWeightKg ?? 0) || net * 1.005;
      return { line, lot, net, bags, gross, derived: !lot?.bagCount };
    });

    const totalNet = rows.reduce((a, r) => a + r.net, 0);
    const totalGross = rows.reduce((a, r) => a + r.gross, 0);
    const totalBags = rows.reduce((a, r) => a + r.bags, 0);

    b.table({
      columns: [
        { header: 'Mark', width: 0.16, render: (r) => r.lot?.bagNumbers || r.line.lotId || '—' },
        { header: 'Lot', width: 0.16, render: (r) => r.line.lotId ?? '—' },
        { header: 'Description', width: 0.26, render: (r) => r.line.description },
        { header: 'Grade', width: 0.12, render: (r) => r.lot?.grade ?? '—' },
        { header: 'Bags', width: 0.1, align: 'right', render: (r) => `${r.bags}${r.derived ? '*' : ''}` },
        { header: 'Net', width: 0.1, align: 'right', render: (r) => num(r.net) },
        { header: 'Gross', width: 0.1, align: 'right', render: (r) => num(r.gross) },
      ],
      rows,
      footRows: [
        ['Total bags', String(totalBags)],
        ['Total net weight', kg(totalNet)],
        ['Total gross weight', kg(totalGross)],
      ],
    });

    const anyDerived = rows.some((r) => r.derived);
    if (anyDerived) {
      b.note(
        '* Bag count derived from net weight at 60 kg per bag because the lot does not record a bag count. ' +
          'Record bag counts and numbers on the lot before the packing list is presented to a bank or customs.',
        'warn',
      );
    }

    const processCounts = new Map<string, number>();
    for (const r of rows) {
      const p = r.lot?.process ?? 'Unspecified';
      processCounts.set(p, (processCounts.get(p) ?? 0) + r.net);
    }
    if (processCounts.size) {
      b.space(4);
      b.sectionTitle('Net weight by process');
      b.table({
        columns: [
          { header: 'Process', width: 0.6, key: 'process' },
          { header: 'Net weight (kg)', width: 0.4, align: 'right', render: (r) => num(r.net) },
        ],
        rows: [...processCounts.entries()].map(([process, net]) => ({ process, net })),
      });
    }

    b.paragraph(
      'Packing: green coffee in 60 kg jute or GrainPro-lined bags, marked as above, palletised for container shipment.',
      { size: 8.5, colour: COLOURS.muted },
    );
    b.signatureBlock({ labels: ['Prepared by', 'Date'] });

    return {
      docType: 'Packing List',
      filename: `${invoice.code}-packing-list.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── proforma invoice ─────────────────────────────────────────────────

  async proformaInvoice(id: string): Promise<RenderedDocument> {
    const proforma = await this.prisma.proformaInvoice.findUnique({
      where: { id },
      include: { buyer: true, lines: true, commercial: true },
    });
    if (!proforma) throw new NotFoundException('Proforma invoice not found');
    const company = await this.company();
    const lotMap = await this.lotsFor(proforma.lines);

    const b = new DocumentBuilder(
      { title: 'Proforma Invoice', reference: proforma.code, company },
      this.footer(company),
    );

    b.keyValues(
      [
        { label: 'Proforma no.', value: proforma.code },
        { label: 'Date', value: dateLong(proforma.date) },
        { label: 'Buyer', value: proforma.buyer?.name },
        { label: 'Country', value: proforma.buyer?.country },
        { label: 'Incoterm', value: proforma.incoterm },
        { label: 'Currency', value: proforma.currency },
        { label: 'Port of loading', value: proforma.portLoading ?? 'Djibouti' },
        { label: 'Port of discharge', value: proforma.portDischarge ?? '—' },
        { label: 'Validity', value: dateLong(proforma.validity) },
        { label: 'Payment terms', value: proforma.paymentTerms ?? '—' },
      ],
      3,
    );

    b.space(6);
    b.sectionTitle('Offer');

    const total = proforma.lines.reduce((a: number, l: any) => a + Number(l.amount ?? 0), 0);
    const totalKg = proforma.lines.reduce((a: number, l: any) => a + Number(l.quantityKg ?? 0), 0);

    b.table({
      columns: [
        { header: '#', width: 0.05, render: (_r, i) => String(i + 1) },
        { header: 'Lot', width: 0.18, key: 'lotId' },
        { header: 'Description', width: 0.34, key: 'description' },
        { header: 'Grade', width: 0.12, render: (r) => (r.lotId ? lotMap.get(r.lotId)?.grade ?? '—' : '—') },
        { header: 'Qty (kg)', width: 0.13, align: 'right', render: (r) => num(r.quantityKg) },
        { header: 'Unit', width: 0.09, align: 'right', render: (r) => num(r.pricePerKg) },
        { header: 'Amount', width: 0.09, align: 'right', render: (r) => money(r.amount, proforma.currency) },
      ],
      rows: proforma.lines,
      emptyText: 'No line items.',
      footRows: [
        ['Total net weight', kg(totalKg)],
        ['TOTAL', money(total, proforma.currency)],
      ],
    });

    b.space(4);
    b.note(
      'This proforma invoice is a non-binding estimate issued for the buyer\'s review and for bank or regulatory reference. ' +
        'It does not constitute an offer capable of acceptance. Quantities and prices are confirmed by the sales contract and the subsequent commercial invoice.',
      'warn',
    );
    b.signatureBlock({ labels: ['For and on behalf of', 'Date'] });

    return {
      docType: 'Proforma Invoice',
      filename: `${proforma.code}-proforma-invoice.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── sales contract ───────────────────────────────────────────────────

  async salesContract(id: string): Promise<RenderedDocument> {
    const contract = await this.prisma.salesContract.findUnique({
      where: { id },
      include: { buyer: true, proforma: { include: { lines: true } }, commercial: { include: { shipments: true } } },
    });
    if (!contract) throw new NotFoundException('Sales contract not found');
    const company = await this.company();

    const b = new DocumentBuilder(
      { title: 'Sales Contract', reference: contract.code, company },
      this.footer(company),
    );

    b.keyValues(
      [
        { label: 'Contract no.', value: contract.code },
        { label: 'Date', value: dateLong(contract.date) },
        { label: 'Seller', value: company.name },
        { label: 'Buyer', value: contract.buyer?.name },
        { label: 'Buyer country', value: contract.buyer?.country },
        { label: 'Incoterm', value: contract.incoterm },
        { label: 'Currency', value: contract.currency },
        { label: 'Contract value', value: money(contract.amount, contract.currency) },
        { label: 'ECTA reference', value: contract.eptaRef ?? '—' },
        { label: 'Signed', value: dateLong(contract.signedAt) },
        { label: 'Proforma reference', value: contract.proforma?.code ?? '—' },
        { label: 'Status', value: contract.status },
      ],
      3,
    );

    b.space(6);
    b.sectionTitle('Goods and quantities');

    const lines = contract.proforma?.lines ?? [];
    const totalKg = lines.reduce((a: number, l: any) => a + Number(l.quantityKg ?? 0), 0);
    b.table({
      columns: [
        { header: 'Lot', width: 0.24, key: 'lotId' },
        { header: 'Description', width: 0.46, key: 'description' },
        { header: 'Quantity', width: 0.3, align: 'right', render: (r) => num(r.quantityKg) },
      ],
      rows: lines,
      emptyText: 'Quantities are described in the attached proforma invoice.',
      footRows: [['Total quantity', kg(totalKg)]],
    });

    b.space(4);
    b.sectionTitle('Terms');
    const terms = [
      `Payment: ${contract.proforma?.paymentTerms ?? 'As agreed between the parties.'}`,
      `Delivery: ${contract.incoterm} ${contract.proforma?.portLoading ?? 'Djibouti'} to ${contract.proforma?.portDischarge ?? contract.buyer?.country ?? 'destination'}.`,
      'Quality: as certified by the Coffee Liquoring Unit at the time of shipment. The quality certificate issued for each lot forms part of this contract.',
      'Documents: commercial invoice, packing list, bill of lading, certificate of origin, phytosanitary certificate, quality certificate and any destination-specific documents required by the importing country.',
      'Origin: the goods are of Ethiopian origin and are covered by an ICO certificate of origin.',
      'Title and risk pass in accordance with the stated Incoterm (Incoterms 2020).',
      'Disputes: the parties will first seek resolution amicably; failing which the dispute is referred to arbitration in Addis Ababa, Ethiopia.',
    ];
    terms.forEach((t, i) => b.paragraph(`${i + 1}.  ${t}`, { size: 9 }));
    b.space(4);
    b.signatureBlock({
      declaration: 'Signed for and on behalf of the parties, who confirm they have authority to bind their respective companies.',
      labels: [`For ${company.name}`, `For ${contract.buyer?.name ?? 'Buyer'}`, 'Date'],
    });

    return {
      docType: 'Sales Contract',
      filename: `${contract.code}-sales-contract.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── quality certificate data (CLU) ───────────────────────────────────

  /**
   * Application data for the Coffee Liquoring Unit certificate.
   *
   * The certificate itself is issued by the CLU. This sheet carries the figures
   * the lab certifies so the application can be lodged, and says so on its face.
   */
  async qualityData(invoiceId: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(invoiceId);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotMap = await this.lotsFor(lines);
    const lots = [...lotMap.values()];

    const b = new DocumentBuilder(
      { title: 'Quality Certificate — Application Data', reference: invoice.code, company },
      this.footer(company),
    );

    b.note(
      'APPLICATION DATA. This sheet is prepared by the exporter to accompany an application for a Coffee Liquoring Unit (CLU) quality certificate. ' +
        'It is not the quality certificate and must not be presented as one. The certificate is issued by the Coffee Liquoring Unit after grading and cupping.',
      'warn',
    );
    b.space(4);

    b.keyValues(
      [
        { label: 'Exporter', value: company.name },
        { label: 'Invoice / consignment', value: invoice.code },
        { label: 'Destination', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: 'Date prepared', value: dateLong(new Date()) },
      ],
      2,
    );

    b.space(4);
    b.sectionTitle('Lots submitted for grading');
    b.table({
      columns: [
        { header: 'Lot', width: 0.18, key: 'lotId' },
        { header: 'Process', width: 0.12, render: (r) => r.process ?? '—' },
        { header: 'Grade', width: 0.1, render: (r) => r.grade ?? '—' },
        { header: 'Screen', width: 0.12, render: (r) => r.screenSize ?? '—' },
        { header: 'Moisture %', width: 0.12, align: 'right', render: (r) => (r.moisturePct != null ? Number(r.moisturePct).toFixed(2) : '—') },
        { header: 'Defects', width: 0.12, align: 'right', render: (r) => (r.defectCount != null ? String(r.defectCount) : '—') },
        { header: 'Cup score', width: 0.12, align: 'right', render: (r) => (r.cuppingScore != null ? Number(r.cuppingScore).toFixed(1) : '—') },
        { header: 'Harvest', width: 0.12, render: (r) => r.harvestYear ?? '—' },
      ],
      rows: lots,
      emptyText: 'No lots are attached to this invoice yet.',
    });

    const missing = lots.filter((l) => l.cuppingScore == null || l.moisturePct == null || l.defectCount == null);
    if (missing.length) {
      b.note(
        `${missing.length} lot(s) are missing moisture, defect or cup score values. The CLU cannot grade a lot without these; ` +
          'record them on the lot before lodging the application.',
        'warn',
      );
    }

    b.space(4);
    b.sectionTitle('Origin declaration');
    b.paragraph(
      lots
        .map((l) => `Lot ${l.lotId}: produced in ${l.origin ?? l.region ?? 'Ethiopia'}, station ${l.station?.name ?? '—'}, harvest ${l.harvestYear ?? '—'}, process ${l.process}.`)
        .join('\n'),
      { size: 9 },
    );
    b.signatureBlock({ labels: ['Prepared by', 'Cupper / QC officer', 'Date'] });

    return {
      docType: 'CLU Quality Certificate',
      filename: `${invoice.code}-clu-application-data.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: false,
    };
  }

  // ── ICO certificate of origin data ───────────────────────────────────

  async icoData(invoiceId: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(invoiceId);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotMap = await this.lotsFor(lines);
    const lots = [...lotMap.values()];
    const totalKg = lines.reduce((a: number, l: any) => a + Number(l.quantityKg ?? 0), 0);

    const b = new DocumentBuilder(
      { title: 'ICO Certificate of Origin — Application Data', reference: invoice.code, company },
      this.footer(company),
    );

    b.note(
      'APPLICATION DATA. Prepared for the International Coffee Organization certificate of origin (ICC-102/9). ' +
        'The certificate is issued and validated by the certifying agency and Ethiopian Customs; this sheet carries the data required for that application.',
      'warn',
    );
    b.space(4);

    // Box numbering follows the ICO certificate layout so the officer can
    // transcribe without hunting for a value.
    b.sectionTitle('Certificate data (box references per ICC-102/9)');
    b.keyValues(
      [
        { label: '1. Exporter', value: company.name },
        { label: '2. Reference', value: invoice.code },
        { label: '3a. Ethiopia (ICO code)', value: '010' },
        { label: '3b. Port of export', value: invoice.portLoading ?? 'Djibouti' },
        { label: '4. Country of production', value: 'Ethiopia (010)' },
        { label: '5. Country of destination', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: '6. Date of export', value: dateLong(invoice.date) },
        { label: '7. Means of transport', value: invoice.shipments?.[0]?.mode ?? 'Sea' },
        { label: '8. ICO mark / UCR', value: lots.map((l) => l.bagNumbers).filter(Boolean).join(', ') || 'to be assigned' },
        { label: '9. Exporter signature', value: company.name },
        { label: '10. Shipping marks', value: invoice.shipments?.[0]?.containerNo ?? '—' },
        { label: '11. Quantity', value: kg(totalKg) },
      ],
      3,
    );

    b.space(4);
    b.sectionTitle('12. Form and type of coffee');
    const forms = [...new Set(lots.map((l) => `${l.form ?? 'Green'} ${l.coffeeType ?? 'Arabica'}`))];
    b.table({
      columns: [
        { header: 'Form / type', width: 0.34, key: 'form' },
        { header: 'Process', width: 0.22, key: 'process' },
        { header: 'Grade', width: 0.16, key: 'grade' },
        { header: 'Net weight', width: 0.28, align: 'right', render: (r) => num(r.net) },
      ],
      rows: lots.map((l, i) => ({ form: forms[i] ?? `${l.form} ${l.coffeeType}`, process: l.process, grade: l.grade, net: l.netWeightKg ?? 0 })),
      emptyText: 'No lots attached.',
    });

    b.note(
      'One certificate of origin is required per form and type of coffee. If this consignment mixes forms, the certifying agency will need a separate certificate for each. ' +
        'The certificate is not required for samples and lots of 60 kg net or less.',
      'info',
    );

    return {
      docType: 'ICO Certificate of Origin',
      filename: `${invoice.code}-ico-application-data.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: false,
    };
  }

  // ── phytosanitary application data ───────────────────────────────────

  async phytosanitaryData(invoiceId: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(invoiceId);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotMap = await this.lotsFor(lines);
    const totalKg = lines.reduce((a: number, l: any) => a + Number(l.quantityKg ?? 0), 0);
    const bags = [...lotMap.values()].reduce((a, l) => a + (l.bagCount ?? 0), 0);

    const b = new DocumentBuilder(
      { title: 'Phytosanitary Certificate — Application Data', reference: invoice.code, company },
      this.footer(company),
    );

    b.note(
      'APPLICATION DATA. Prepared for an application to the Ethiopian Plant Health Institute / Ministry of Agriculture under the IPPC. ' +
        'The phytosanitary certificate is issued by the national plant protection organisation after inspection; this sheet only carries the application data. ' +
        'Do not present this sheet as a phytosanitary certificate.',
      'warn',
    );
    b.space(4);

    b.keyValues(
      [
        { label: 'Exporter / consignor', value: company.name },
        { label: 'Consignment reference', value: invoice.code },
        { label: 'Country of origin', value: 'Ethiopia' },
        { label: 'Destination country', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: 'Botanical name', value: 'Coffea arabica' },
        { label: 'Declared quantity', value: kg(totalKg) },
        { label: 'Number of packages', value: bags ? `${bags} bags` : 'to be confirmed' },
        { label: 'Distinguishing marks', value: invoice.shipments?.[0]?.containerNo ?? '—' },
        { label: 'Means of transport', value: invoice.shipments?.[0]?.mode ?? 'Sea' },
        { label: 'Place of issue', value: 'Addis Ababa, Ethiopia' },
      ],
      2,
    );

    b.space(4);
    b.note(
      'Ethiopian practice is to apply approximately 5 to 10 business days before shipment and the certificate is commonly valid for around 14 days. ' +
        'Those timings are recorded here as planning guidance only and have not been confirmed against a primary source — confirm them with the Plant Health Directorate before scheduling a shipment against them.',
      'muted',
    );

    b.signatureBlock({ labels: ['Applicant', 'Date'] });

    return {
      docType: 'Phytosanitary Certificate',
      filename: `${invoice.code}-phytosanitary-application-data.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: false,
    };
  }

  // ── EUDR dossier ─────────────────────────────────────────────────────

  async eudrDossier(invoiceId: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(invoiceId);
    const company = await this.company();
    const lines = this.invoiceLines(invoice);
    const lotIds = [...new Set(lines.map((l: any) => l.lotId).filter(Boolean))] as string[];

    const traces = lotIds.length
      ? await this.prisma.lotTrace.findMany({
          where: { lotId: { in: lotIds } },
          include: { plot: { include: { producer: true } } },
        })
      : [];

    const byPlot = new Map<string, any>();
    for (const t of traces) {
      const cur = byPlot.get(t.plotId) ?? { plot: t.plot, lots: new Set<string>(), kg: 0 };
      cur.lots.add(t.lotId);
      cur.kg += Number(t.contributedKg ?? 0);
      byPlot.set(t.plotId, cur);
    }
    const plots = [...byPlot.values()];

    const b = new DocumentBuilder(
      { title: 'EUDR Due Diligence — Geolocation Dossier', reference: invoice.code, company },
      this.footer(company),
    );

    b.note(
      'This dossier supplies the production plot data the EU importer needs in order to file a Due Diligence Statement under Regulation (EU) 2023/1115. ' +
        'The statement itself is submitted by the EU importer or operator in the EUDR Information System. Neither the exporter nor this document constitutes a filed statement.',
      'info',
    );
    b.space(4);

    b.keyValues(
      [
        { label: 'Consignment', value: invoice.code },
        { label: 'Commodity', value: 'Coffee' },
        { label: 'HS code', value: invoice.hsCode },
        { label: 'Country of production', value: 'Ethiopia' },
        { label: 'Destination', value: invoice.destinationCountryName ?? invoice.buyer?.country },
        { label: 'Plots declared', value: String(plots.length) },
        { label: 'Geolocated plots', value: String(plots.filter((p) => p.plot.polygon).length) },
        { label: 'Production period', value: [...new Set(lines.map((l: any) => l.lotId))].length ? 'see harvest year per lot' : '—' },
      ],
      2,
    );

    b.space(4);
    b.sectionTitle('Plots contributing to this consignment');
    b.table({
      columns: [
        { header: 'Plot', width: 0.16, render: (r) => r.plot.id.slice(0, 10) },
        { header: 'Producer', width: 0.2, render: (r) => r.plot.producer?.name ?? '—' },
        { header: 'Type', width: 0.13, render: (r) => r.plot.producer?.kind ?? '—' },
        { header: 'Woreda / Kebele', width: 0.2, render: (r) => [r.plot.woreda, r.plot.kebele].filter(Boolean).join(' / ') || '—' },
        { header: 'Area ha', width: 0.09, align: 'right', render: (r) => (r.plot.areaHa != null ? Number(r.plot.areaHa).toFixed(3) : '—') },
        { header: 'Geodata', width: 0.1, render: (r) => (r.plot.polygon ? (Number(r.plot.areaHa ?? 0) > 4 ? 'Polygon' : 'Point/Polygon') : 'MISSING') },
        { header: 'Lots', width: 0.12, render: (r) => [...r.lots].join(', ') },
      ],
      rows: plots,
      emptyText: 'No production plots are linked to the lots on this invoice.',
    });

    const missing = plots.filter((p) => !p.plot.polygon);
    if (!plots.length || missing.length) {
      b.note(
        !plots.length
          ? 'This consignment cannot be supported for EUDR. No plot data is linked to the lots, and a Due Diligence Statement cannot be filed without the geolocation of every contributing plot. Link the contributing farms to the lots before shipment.'
          : `${missing.length} plot(s) have no geolocation recorded. EUDR requires six-decimal coordinates — a polygon for plots over 4 hectares, and at least a single point below that. The importer cannot file a compliant statement until these are supplied.`,
        'warn',
      );
    }

    b.space(4);
    b.sectionTitle('Machine-readable geolocation');
    const collection = {
      type: 'FeatureCollection',
      features: plots
        .filter((p) => p.plot.polygon)
        .map((p) => ({
          type: 'Feature',
          geometry: p.plot.polygon,
          properties: {
            plotId: p.plot.id,
            producer: p.plot.producer?.name,
            producerKind: p.plot.producer?.kind,
            woreda: p.plot.woreda,
            kebele: p.plot.kebele,
            areaHa: p.plot.areaHa ? Number(p.plot.areaHa) : null,
            lots: [...p.lots],
          },
        })),
    };
    b.paragraph(
      'The GeoJSON FeatureCollection for this consignment is available from the API at ' +
        `GET /api/traceability/eudr/{shipmentId}/geojson and can be supplied to the importer as a file. ` +
        `This consignment declares ${collection.features.length} geolocated plot(s).`,
      { size: 8.5, colour: COLOURS.muted },
    );

    return {
      docType: 'EUDR Plot Geolocation Dossier',
      filename: `${invoice.code}-eudr-geolocation-dossier.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── generic control sheet ────────────────────────────────────────────

  /**
   * Control sheet for documents we do not issue: a bill of lading, an insurance
   * certificate, a customs declaration.
   *
   * Every row in the pack is printable, but this sheet states what the document
   * is, who issues it, and its current status. It is explicitly not the
   * document, which is the only honest way to make a third-party document
   * printable.
   */
  async controlSheet(invoiceId: string, docType: string): Promise<RenderedDocument> {
    const invoice = await this.loadInvoice(invoiceId);
    const company = await this.company();
    const doc = invoice.documents.find((d) => d.docType === docType);

    const b = new DocumentBuilder(
      { title: `${docType} — Control Sheet`, reference: invoice.code, company },
      this.footer(company),
    );

    b.note(
      `DOCUMENT CONTROL SHEET. "${docType}" is issued by a third party and is not produced by this system. ` +
        'This sheet records what the document is, who issues it, and its status on this consignment. It is not the document itself and does not replace it.',
      'warn',
    );
    b.space(4);

    b.keyValues(
      [
        { label: 'Consignment', value: invoice.code },
        { label: 'Document', value: docType },
        { label: 'Status', value: doc?.status ?? 'Pending' },
        { label: 'Issued by', value: doc?.authority ?? '—' },
        { label: 'Required', value: doc?.mandatory ? 'Yes — mandatory' : 'Conditional' },
        { label: 'Reference', value: doc?.reference ?? 'not yet issued' },
        { label: 'Target date', value: doc?.validUntil ? dateLong(doc.validUntil) : '—' },
        { label: 'Submission', value: doc?.submissionMethod ?? '—' },
      ],
      2,
    );

    if (doc?.legalBasis) {
      b.space(2);
      b.sectionTitle('Legal basis');
      b.paragraph(doc.legalBasis, { size: 9 });
    }
    if (doc?.officialUrl) {
      b.space(2);
      b.sectionTitle('Authority source');
      b.paragraph(doc.officialUrl, { size: 8.5, colour: COLOURS.muted });
    }
    if (doc?.notes) {
      b.space(2);
      b.sectionTitle('Notes');
      b.paragraph(doc.notes, { size: 9 });
    }

    b.space(4);
    b.sectionTitle('Consignment summary');
    b.paragraph(
      `Buyer: ${invoice.buyer?.name ?? '—'}\nDestination: ${invoice.destinationCountryName ?? invoice.buyer?.country ?? '—'}\n` +
        `Incoterm: ${invoice.incoterm}\nInvoice date: ${dateLong(invoice.date)}`,
      { size: 9 },
    );

    return {
      docType,
      filename: `${invoice.code}-${slug(docType)}-control-sheet.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: false,
    };
  }

  // ── payroll ──────────────────────────────────────────────────────────

  private monthName(m: number) {
    return ['January','February','March','April','May','June','July','August','September','October','November','December'][m - 1] ?? String(m);
  }

  /** Payroll register: every line for a month, with the statutory totals. */
  async payrollRegister(runId: string): Promise<RenderedDocument> {
    const run = await this.prisma.payrollRun.findUnique({
      where: { id: runId },
      include: { lines: { orderBy: { employeeName: 'asc' } } },
    });
    if (!run) throw new NotFoundException('Payroll run not found');
    const company = await this.company();
    const period = `${this.monthName(run.periodMonth)} ${run.periodYear}`;

    const b = new DocumentBuilder(
      { title: 'Payroll Register', reference: `${run.code} · ${period}`, company },
      this.footer(company),
    );

    const n = (v: unknown) => Number(v ?? 0);

    b.keyValues(
      [
        { label: 'Payroll run', value: run.code },
        { label: 'Period', value: period },
        { label: 'Status', value: run.status },
        { label: 'Employees', value: String(run.employeeCount) },
        { label: 'Prepared', value: dateLong(run.date) },
        { label: 'Currency', value: 'ETB' },
      ],
      3,
    );

    b.space(6);
    b.sectionTitle('Register');

    b.table({
      columns: [
        { header: '#', width: 0.04, render: (_r, i) => String(i + 1) },
        { header: 'Employee', width: 0.19, key: 'employeeName' },
        { header: 'Type', width: 0.1, render: (r) => (r.employmentType === 'PERMANENT' ? 'Perm.' : 'Contract') },
        { header: 'Basic', width: 0.13, align: 'right', render: (r) => num(r.basicSalary) },
        { header: 'Allow.', width: 0.11, align: 'right', render: (r) => num(r.allowances) },
        { header: 'Gross', width: 0.13, align: 'right', render: (r) => num(r.grossPay) },
        { header: 'Income tax', width: 0.12, align: 'right', render: (r) => num(r.incomeTax) },
        { header: 'Pension 7%', width: 0.11, align: 'right', render: (r) => num(r.employeePension) },
        { header: 'Net pay', width: 0.13, align: 'right', render: (r) => num(r.netPay) },
      ],
      rows: run.lines,
      emptyText: 'No employees in this run.',
      footRows: [
        ['Total gross', num(run.totalGross)],
        ['Total income tax', num(run.totalIncomeTax)],
        ['Total employee pension (7%)', num(run.totalEmployeePension)],
        ['Total other deductions', num(run.totalOtherDeductions)],
        ['TOTAL NET PAY', num(run.totalNet)],
      ],
    });

    b.space(4);
    b.sectionTitle('Employer contributions and cost');
    b.table({
      columns: [
        { header: 'Item', width: 0.6, key: 'item' },
        { header: 'Amount ETB', width: 0.4, align: 'right', render: (r) => num(r.amount) },
      ],
      rows: [
        { item: 'Gross salaries', amount: n(run.totalGross) },
        { item: 'Employer pension (11%)', amount: n(run.totalEmployerPension) },
        { item: 'Total employer cost', amount: n(run.totalEmployerCost) },
        { item: 'Income tax remittable to the Ministry of Revenues', amount: n(run.totalIncomeTax) },
        {
          item: 'Pension remittable (employee 7% + employer 11%)',
          amount: n(run.totalEmployeePension) + n(run.totalEmployerPension),
        },
      ],
    });

    b.note(
      'Income tax is charged on gross taxable income under the Federal Income Tax Amendment Proclamation No. 1395/2025, ' +
        'effective 1 July 2025. Pension is 7% employee and 11% employer under the Private Organization Employees Pension ' +
        'Proclamation No. 715/2011. The employee contribution is withheld after income tax, not before it.',
      'muted',
    );

    b.signatureBlock({
      declaration: 'Prepared by the payroll officer and approved by the authorised signatory.',
      labels: ['Prepared by', 'Approved by', 'Date'],
    });

    return {
      docType: 'Payroll Register',
      filename: `${run.code}-payroll-register-${run.periodYear}-${String(run.periodMonth).padStart(2, '0')}.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  /** Individual payslip. */
  async payslip(runId: string, lineId: string): Promise<RenderedDocument> {
    const line = await this.prisma.payrollLine.findUnique({ where: { id: lineId }, include: { run: true } });
    if (!line || line.runId !== runId) throw new NotFoundException('Payslip not found');
    const company = await this.company();
    const run = line.run;
    const period = `${this.monthName(run.periodMonth)} ${run.periodYear}`;
    const n = (v: unknown) => Number(v ?? 0);

    const b = new DocumentBuilder(
      { title: 'Payslip', reference: `${line.employeeCode} · ${period}`, company },
      `${company.name} · Payslip ${period} · confidential`,
    );

    b.keyValues(
      [
        { label: 'Employee', value: line.employeeName },
        { label: 'Employee code', value: line.employeeCode },
        { label: 'Position', value: line.position ?? '—' },
        { label: 'Employment type', value: line.employmentType === 'PERMANENT' ? 'Permanent' : 'Contract' },
        { label: 'Pay period', value: period },
        { label: 'Payroll run', value: run.code },
      ],
      2,
    );

    b.space(6);
    b.sectionTitle('Earnings');
    b.table({
      columns: [
        { header: 'Item', width: 0.7, key: 'item' },
        { header: 'Amount ETB', width: 0.3, align: 'right', render: (r) => num(r.amount) },
      ],
      rows: [
        { item: 'Basic salary', amount: n(line.basicSalary) },
        { item: 'Allowances', amount: n(line.allowances) },
        ...(n(line.overtime) > 0 ? [{ item: 'Overtime', amount: n(line.overtime) }] : []),
      ],
      footRows: [['Gross pay', num(line.grossPay)]],
    });

    b.space(4);
    b.sectionTitle('Deductions');
    b.table({
      columns: [
        { header: 'Item', width: 0.7, key: 'item' },
        { header: 'Amount ETB', width: 0.3, align: 'right', render: (r) => num(r.amount) },
      ],
      rows: [
        { item: 'Income tax (PAYE)', amount: n(line.incomeTax) },
        ...(line.pensionEligible ? [{ item: 'Pension contribution (7%)', amount: n(line.employeePension) }] : []),
        ...(n(line.otherDeductions) > 0 ? [{ item: 'Other deductions', amount: n(line.otherDeductions) }] : []),
      ],
      footRows: [['Total deductions', num(n(line.incomeTax) + n(line.employeePension) + n(line.otherDeductions))]],
    });

    b.space(6);
    b.table({
      columns: [
        { header: 'Net pay', width: 0.7, render: () => 'NET PAY' },
        { header: 'Amount ETB', width: 0.3, align: 'right', render: () => num(line.netPay) },
      ],
      rows: [{}],
    });

    b.space(2);
    b.sectionTitle('Employer contributions (not deducted from pay)');
    b.table({
      columns: [
        { header: 'Item', width: 0.7, key: 'item' },
        { header: 'Amount ETB', width: 0.3, align: 'right', render: (r) => num(r.amount) },
      ],
      rows: line.pensionEligible
        ? [
            { item: 'Employer pension contribution (11%)', amount: n(line.employerPension) },
            { item: 'Total cost of employment', amount: n(line.employerCost) },
          ]
        : [{ item: 'No pension contribution for this employment type', amount: 0 }],
    });

    if (line.notes) {
      b.space(3);
      b.note(line.notes, 'muted');
    }

    b.note(
      'Tax is charged on gross taxable income under the Federal Income Tax Amendment Proclamation No. 1395/2025. ' +
        'Where shown, the pension contribution is 7% of salary under the Private Organization Employees Pension Proclamation No. 715/2011.',
      'muted',
    );

    b.signatureBlock({ labels: ['Employee signature', 'Date'] });

    return {
      docType: 'Payslip',
      filename: `payslip-${line.employeeCode}-${run.periodYear}-${String(run.periodMonth).padStart(2, '0')}.pdf`,
      buffer: await b.toBuffer(),
      isPrimaryDocument: true,
    };
  }

  // ── dispatcher ───────────────────────────────────────────────────────

  /**
   * Render the PDF for a given document type on an invoice.
   *
   * Types not explicitly handled fall through to a control sheet, so every
   * document in the pack has a printable artefact.
   */
  async renderForInvoice(invoiceId: string, docType: string): Promise<RenderedDocument> {
    switch (docType) {
      case 'Commercial Invoice':
        return this.commercialInvoice(invoiceId);
      case 'Packing List':
        return this.packingList(invoiceId);
      case 'CLU Quality Certificate':
        return this.qualityData(invoiceId);
      case 'ICO Certificate of Origin':
        return this.icoData(invoiceId);
      case 'Phytosanitary Certificate':
        return this.phytosanitaryData(invoiceId);
      case 'EUDR Plot Geolocation Dossier':
      case 'EUDR Due Diligence Statement':
        return this.eudrDossier(invoiceId);
      default: {
        if (AUTHORITY_ISSUED.has(docType)) return this.controlSheet(invoiceId, docType);
        return this.controlSheet(invoiceId, docType);
      }
    }
  }

  /**
   * Every PDF that should accompany a consignment.
   *
   * Scoped to documents that are actually applicable (not retracted) and to the
   * ones we can produce, so an email does not carry a pile of control sheets for
   * irrelevant rows.
   */
  async packForInvoice(invoiceId: string): Promise<RenderedDocument[]> {
    const invoice = await this.loadInvoice(invoiceId);
    const applicable = invoice.documents.filter((d) => d.status !== 'NotApplicable');

    const produce = new Set([
      'Commercial Invoice',
      'Packing List',
      'CLU Quality Certificate',
      'ICO Certificate of Origin',
      'Phytosanitary Certificate',
      'EUDR Plot Geolocation Dossier',
      'EUDR Due Diligence Statement',
    ]);

    const wanted = applicable.filter((d) => produce.has(d.docType));
    const out: RenderedDocument[] = [];
    for (const doc of wanted) {
      try {
        out.push(await this.renderForInvoice(invoiceId, doc.docType));
      } catch (e) {
        // One failed renderer must not stop the email; the rest of the pack
        // still goes out and the failure is visible in the log.
        this.logger.error(`Failed to render ${doc.docType} for invoice ${invoice.code}: ${(e as Error).message}`);
      }
    }
    return out;
  }
}

// ── helpers ────────────────────────────────────────────────────────────

function slug(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ONES = [
  '', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen',
];
const TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];

function below1000(n: number): string {
  if (n === 0) return '';
  if (n < 20) return ONES[n];
  if (n < 100) return `${TENS[Math.floor(n / 10)]}${n % 10 ? `-${ONES[n % 10]}` : ''}`;
  return `${ONES[Math.floor(n / 100)]} hundred${n % 100 ? ` and ${below1000(n % 100)}` : ''}`;
}

/** Amount in words, the form most banks and customs still expect on an invoice. */
export function amountInWords(amount: number, currency = 'USD'): string {
  const names: Record<string, string> = { USD: 'US dollars', EUR: 'euro', GBP: 'pounds sterling', ETB: 'birr' };
  const unit = names[currency] ?? currency;
  const whole = Math.floor(Math.abs(amount));
  const cents = Math.round((Math.abs(amount) - whole) * 100);

  if (whole === 0 && cents === 0) return `Zero ${unit} only.`;

  const scale: [number, string][] = [
    [1_000_000_000, 'billion'],
    [1_000_000, 'million'],
    [1_000, 'thousand'],
  ];
  let rest = whole;
  const parts: string[] = [];
  for (const [value, label] of scale) {
    const count = Math.floor(rest / value);
    if (count) {
      parts.push(`${below1000(count)} ${label}`);
      rest %= value;
    }
  }
  if (rest) parts.push(below1000(rest));

  const words = parts.join(' ').replace(/\s+/g, ' ').trim();
  const centsPart = cents ? ` and ${below1000(cents)} cents` : '';
  const capitalised = words.charAt(0).toUpperCase() + words.slice(1);
  return `${capitalised} ${unit}${centsPart} only.`;
}
